import Layouts from "@/components/layouts/Layouts";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { yekanBakh } from "@/utils/fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekanBakh.className}>
        <div className="container">
          <NextAuthProvider>
            <Layouts>{children}</Layouts>
          </NextAuthProvider>
        </div>
      </body>
    </html>
  );
}
